#!/usr/bin/env zsh

# Create a new git worktree

# slugify from https://stackoverflow.com/a/63286099
slugify () {
    echo "$1" | iconv -c -t ascii//TRANSLIT | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z
}

branch=${1}
dir_name=${2:-$(slugify branch)}

root=$(git rev-parse --show-toplevel)
bare="$root/../.bare"
if [ -d "$bare" ]; then
    path="${root}/../${dir_name}"
    git worktree add -b "$branch" "$path" $@ && pushd "$path"
else
    echo "TODO: Configure for non-bare repository"
fi
