#!/usr/bin/env bash
pushd() {
  command pushd "$@" >/dev/null
}

popd() {
  command popd "$@" >/dev/null
}

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="tools/dotbot"

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pushd "${DOTFILES}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${DOTBOT_DIR}/bin/dotbot" \
  -d "${BASEDIR}" \
  --plugin-dir tools/dotbot-plugins/dotbot-brew \
  -c "${CONFIG}" "${@}"

popd
