default_context:
    full_name: "Adam Jackman"
    email: "adam@acjackman.com"
    github_username: "acjackman"
abbreviations:
    pp: https://github.com/audreyr/cookiecutter-pypackage.git
    gh: https://github.com/{0}.git
    bb: https://bitbucket.org/{0}
