tap "homebrew/cask"
tap "homebrew/core"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "railwaycat/emacsmacport"
brew "mas"

# *Nix utils
brew "direnv"
brew "duti"
brew "tldr"
brew "tree"
brew "fzf"
brew "svn"

# Dev/Data Tools:
brew "awscli"
brew "git"
brew "hub"
brew "jq"
brew "yq"
brew "yj"
brew "pandoc"
brew "pipx"
brew "pyenv"
brew "pyenv-virtualenv"
brew "r"
brew "rsync"
brew "terraform"
brew "gh"
brew "diff-so-fancy"
cask "docker"
cask "iterm2"
cask "kaleidoscope"
cask "tower"
cask "transmit"
cask "tad"  # CSV Viewer
cask "dash"
mas "Patterns", id: 429449079
cask "firefox"
cask "google-chrome"
brew "ripgrep"
brew "coreutils"
brew "fd"

# Organization
cask "slack"
cask "omnifocus"
cask "textexpander"
cask "dropbox"
cask "1password"
cask "fantastical"
# cask "mimestream"  # TODO: Make cask of MIMEStream

cask "obsidian"
mas "GoodNotes", id: 1480793815
mas "Instapaper", id: 1481302432
mas "Drafts", id: 1435957248

# Customization/Utilities
cask "amethyst"
cask "contexts"
cask "karabiner-elements"
cask "launchbar"
cask "hammerspoon"
mas "Dark Mode for Safari", id: 1397180934
cask "setapp"
cask "backblaze"
cask "iina"
mas "CARROT Weather", id: 993487541
brew "libusb" # used for Ergodox EZ keyboard flashing
brew "noti"
cask "qmk-toolbox"
cask "keybase"
brew "topgrade"
cask "bartender"
cask "marked"
cask "soulver"
#mas "ToothFairy", id: 1191449274
#mas "Shush - Microphone Manager", id: 496437906
#cask "logitech-camera-settings"
#cask "logitech-options"
mas "TextSniper", id: 1528890965


# Fonts
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-source-sans-pro"
cask "font-montserrat-alternates"
cask "font-source-code-pro"
