# themes from https://github.com/alacritty/alacritty-theme

# import = ["/Users/mischa/.config/alacritty/themes/themes/gruvbox_dark.toml"]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[shell]
program = "/opt/jackman/bin/tmux_chooser.sh"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[cursor]
unfocused_hollow = true
